### PR TITLE
Multiline formatting

### LINKED ISSUE #36: [macOS] Cannot modify the font for multiple lines when some html tags are present
**GENERAL**

**App Version:** 3.4.1
**Platform:** macOS
**OS Version:** 10.13.6 (High Sierra)
**Editor:** Plus

**ISSUE**

When trying to apply a new font-family or point size to multiple lines of text one of which is a blank line, the latter will cause the font change to be applied only to the text above the blank line.

The cause appeared to be the presence of a `<br>` tag with no preceding text however I was able to reproduce the issue without the blank line.  I basically replaced the `<br>` tag  with `<p></p>` and no text in between and the issue persisted.

**EXPECTED BEHAVIOR**

The new font selection is applied to all selected lines regardless of having blank lines or empty  `<p>` tags.

**STEPS TO RECREATE**

1. Create a new note with the following lines:
 **LINE 1:** "Header-1"
 **LINE 2:** LEAVE BLANK
 **LINE 3:** "line 1"
 **LINE 4:** "line 2"
 **LINE 5:** "line 4"
7. Highlight all lines of text & change the font-family or pitch size.
8. Note the change is applied only to the first line; in this case the "Header-1" line which is the only text above the blank line.
9. Add a new line of text just after "Header-1"; have this read "Header-2".
10. Highlight all lines of text & change the font-family or pitch size.
11. Note that now the font change is applied only to the first 2 lines of text both of which are above the blank line.
12. Add some text on only the blank line.
13. Highlight all lines of text & change the font-family or pitch size.
14. Note that now the font change is applied to all lines of text.
15. Remove the text just added to the blank line.
16. Highlight all lines of text & change the font-family or pitch size.
17. Note that again, the font change is applied only to the first two lines of text.

### PR DESCRIPTION
**Pull request by ningsongshen**
Fixes #36 by redoing RTL support I added a while back (now applying only to block-level elements). I chose to investigate RTL because the issue disappeared when I disabled it.

Interesting because they reported the issue way before I made any of those RTL changes, but I can't seem to find anything else that affects it. 

Summernote editor works fine so this is definitely on our end.

Note: branch is off of cursor-color so that PR (https://github.com/standardnotes/plus-editor/pull/35) needs to be merged first.

### CODE REVIEW

File: src/main.js [hunk 1]
```diff
@@ -7,6 +7,14 @@ document.addEventListener("DOMContentLoaded", function (event) {
   let ignoreTextChange = false;
   let newNoteLoad = true,
     didToggleFullScreen = false;
+  
+  // Keep this variable up top so that it only needs to be loaded once.
```
Comment (atmoio) [inline src/main.js:11]: This comment is not necessary as it's typically clear why we would define something up top ;)
